package main

import (
	"fmt"
	"html"
	"math"
	"strings"
)

func f2(v float64) string {
	if math.IsNaN(v) {
		return "n/a"
	}
	return fmt.Sprintf("%.2f", v)
}

func f3(v float64) string {
	if math.IsNaN(v) {
		return "n/a"
	}
	return fmt.Sprintf("%.3f", v)
}

func pval(v float64) string {
	if math.IsNaN(v) {
		return "n/a"
	}
	mark := "✓"
	if v < 0.01 {
		mark = "✗"
	}
	if v < 1e-4 {
		return fmt.Sprintf("%s %.1e", mark, v)
	}
	return fmt.Sprintf("%s %.3f", mark, v)
}

func mbps(v float64) string {
	switch {
	case v >= 1000:
		return fmt.Sprintf("%.2f GB/s", v/1000)
	case v >= 1:
		return fmt.Sprintf("%.1f MB/s", v)
	default:
		return fmt.Sprintf("%.1f KB/s", v*1000)
	}
}

func markdown(r Result) string {
	var b strings.Builder
	p := func(format string, args ...any) { fmt.Fprintf(&b, format, args...) }

	p("# racerand benchmarks\n\n")
	p("Run started %s; generated by `racerand-bench`.\n\n", r.Generated.UTC().Format("2006-01-02 15:04:05 UTC"))
	p("| | |\n|---|---|\n")
	p("| CPU | %s |\n", r.Machine.CPU)
	p("| Cores | %d (GOMAXPROCS %d) |\n", r.Machine.NumCPU, r.Machine.GOMAXPROCS)
	p("| OS / arch | %s / %s |\n", r.Machine.OS, r.Machine.Arch)
	p("| Go | %s |\n", r.Machine.GoVersion)
	p("| Quality sample | %v bytes per generator |\n", r.Config["quality_bytes"])
	p("| Throughput window | %v per measurement |\n", r.Config["throughput_dur"])
	p("| Sweep samples | %v raw samples per point |\n\n", r.Config["sweep_samples"])
	p("These are single-run measurements, not entropy or security guarantees. The jitter rows use this repository's small timing baseline, not jitterentropy or HAVEGE. H values are assumptions. Errors record rejected configurations or interrupted measurements.\n\n")

	p("Contents: [example output](#what-the-output-looks-like) · [throughput](#throughput) · [Uint64](#uint64-cost) · [quality](#statistical-quality) · [NIST](#nist-sp-800-22-subset) · [worker sweep](#raw-source-worker-sweep) · [variants](#raw-source-variants) · [GOMAXPROCS](#gomaxprocs-sweep) · [latency](#latency) · [go test -bench](#go-test--bench) · [method](#method)\n\n")

	if len(r.Noise) > 0 {
		p("## What the output looks like\n\n")
		p("Image samples: %v bytes per generator, collected %v.\n\n", r.Config["noise_bytes"], r.Config["noise_generated"])
		p("Example output from each generator, unprocessed. **Bytes**: 64 KiB as 256×256 grayscale pixels, one byte per pixel. **Bits**: 8 KiB as 256×256 black-and-white pixels, one bit per pixel. **Lag plot**: a 256×256 density map of consecutive byte pairs (x = byte *i*, y = byte *i+1*, origin bottom-left) over the whole sample, log-scaled; independent uniform bytes give even noise, serial structure gives lines and hot spots. Each lag image has its own brightness scale. Images use separate samples from the statistical tests; visible uniformity does not prove unpredictability.\n\n")
		p("| Generator | Bytes | Bits | Lag plot | First 32 bytes |\n|---|---|---|---|---|\n")
		for _, row := range r.Noise {
			if row.Err != "" || len(row.Hex) != 64 {
				p("| %s | error: %s | | | |\n", row.Name, row.Err)
				continue
			}
			p("| %s | <img src=\"%s\" width=\"128\" alt=\"%s bytes\"> | <img src=\"%s\" width=\"128\" alt=\"%s bits\"> | <img src=\"%s\" width=\"128\" alt=\"%s lag plot\"> | `%s`<br>`%s` |\n",
				html.EscapeString(row.Name), html.EscapeString(row.Gray), html.EscapeString(row.Name), html.EscapeString(row.Bits), html.EscapeString(row.Name), html.EscapeString(row.Lag), html.EscapeString(row.Name), row.Hex[:32], row.Hex[32:])
		}
		p("\n")
	}

	p("## Throughput\n\n")
	p("Bytes delivered per second through `io.Reader`. The racerand raw and TRNG rows run with persistent workers, so they also occupy `workers` cores while reading; DRBG workers run during startup and reseeding. Throughput is delivered output, not an entropy rate.\n\n")
	p("| Generator | Family | 64 B reads | 64 KiB reads |\n|---|---|---:|---:|\n")
	for _, row := range r.Throughput {
		if row.Err != "" {
			p("| %s | %s | error: %s | |\n", row.Name, row.Family, row.Err)
			continue
		}
		p("| %s | %s | %s | %s |\n", row.Name, row.Family, mbps(row.MBps64), mbps(row.MBps64K))
	}

	p("\n## Uint64 cost\n\n")
	p("Nanoseconds per `Uint64()` call. racerand takes a mutex on every call because a Reader is safe for concurrent use; the local math/rand generators do not. crypto/rand supports concurrent reads. The duration harness includes function-call overhead.\n\n")
	p("| Generator | ns/op |\n|---|---:|\n")
	for _, row := range r.Uint64 {
		if row.Err != "" {
			p("| %s | error: %s |\n", row.Name, row.Err)
			continue
		}
		p("| %s | %.2f |\n", row.Name, row.NsPerOp)
	}

	p("\n## Statistical quality\n\n")
	p("Distribution diagnostics inspired by ent and SP 800-90B on %v bytes from each generator. Ideal values: Shannon 8, MCV byte 8, conditional 8, Markov 1, chi-square p away from 0 and 1, mean 127.5, pi error 0, serial correlation 0, compression ratio about 1. Finite samples lower the frequency estimates even for good generators. Conditional and Markov columns are simplified diagnostics, not validated entropy bounds.\n\n", r.Config["quality_bytes"])
	p("| Generator | Shannon (bits/B) | MCV min-entropy (bits/B) | Cond. min-entropy (bits/B) | Markov (bits/bit) | χ² p | Mean | π error %% | Serial corr. | Compression |\n|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|\n")
	for _, row := range r.Quality {
		if row.Err != "" {
			p("| %s | error: %s | | | | | | | | |\n", row.Name, row.Err)
			continue
		}
		q := row.Report
		p("| %s | %s | %s | %s | %s | %s | %s | %s | %s | %s |\n", row.Name,
			f3(q.ShannonEntropy), f2(q.MinEntropyByte), f2(q.CondMinEntropy), f3(q.MarkovMinEntropy),
			f3(q.ChiSquareP), f2(q.Mean), f2(q.MonteCarloPiErrPct), fmt.Sprintf("%.4f", q.SerialCorrelation), f3(q.CompressionRatio))
	}

	p("\n## NIST SP 800-22 subset\n\n")
	p("p-values at α = 0.01 on the same data. ✓ is p ≥ 0.01. Eleven p-values are reported, including multiple results from some test families. Occasional failures are expected at this significance level. Neither passing nor failing establishes cryptographic security; n/a means the test was not applicable.\n\n")
	if len(r.Quality) > 0 {
		var names []string
		for _, q := range r.Quality {
			if len(q.NIST) > 0 {
				for _, t := range q.NIST {
					names = append(names, t.Name)
				}
				break
			}
		}
		p("| Generator | Passed |")
		for _, n := range names {
			p(" %s |", n)
		}
		p("\n|---|---:|")
		for range names {
			p("---:|")
		}
		p("\n")
		for _, row := range r.Quality {
			if row.Err != "" {
				continue
			}
			p("| %s | %d/%d |", row.Name, row.Passed, row.Total)
			for _, t := range row.NIST {
				p(" %s |", pval(t.P))
			}
			p("\n")
		}
	}

	sweepHeader := func() {
		p("| Point | Workers | ns/sample | MCV (bits/sample) | Pair diagnostic | Shannon | Folded byte MCV | Folded byte Shannon | MCV × sample rate | Seed @H=0.5 | Seed @H=MCV |\n|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|\n")
	}
	sweepRow := func(row SweepRow) {
		p("| %s | %d | %.0f | %s | %s | %s | %s | %s | %.1f Mbit/s | %.0f µs | %.0f µs |\n",
			row.Label, row.Workers, row.NsPerSample, f2(row.MCV), f2(row.Cond), f2(row.Shannon),
			f2(row.FoldMCV), f2(row.FoldShannon), row.RateMbit, row.SeedMicros, row.CalMicros)
	}

	p("\n## Raw source: worker sweep\n\n")
	p("The atomic source with feedback, sampled directly through `Harvester.Sample` (no health tests, no conditioning). MCV is the most-common-value min-entropy estimate on the full 64-bit sample; the pair column is a frequency-based next-sample guessing diagnostic. Seed columns estimate harvesting time for a 256-bit seed under H=0.5 and under the observed MCV (2x oversampling included). MCV times sample rate ignores correlation and is not a validated entropy rate. Do not use these columns to choose security parameters.\n\n")
	sweepHeader()
	for _, row := range r.Workers {
		sweepRow(row)
	}

	p("\n## Raw source: variants\n\n")
	p("Access discipline (atomic vs. plain unsynchronized loads and stores) and the chaotic feedback loop, at one worker and at the default worker count.\n\n")
	sweepHeader()
	for _, row := range r.Variants {
		sweepRow(row)
	}

	p("\n## GOMAXPROCS sweep\n\n")
	p("The default worker count is GOMAXPROCS-1. With GOMAXPROCS=1 workers and sampler share one execution slot; explicit yields and preemption affect sampling, and `New` refuses to start.\n\n")
	p("| Point | Workers | Samples | ns/sample | MCV (bits/sample) | Pair diagnostic | Shannon | New() |\n|---|---:|---:|---:|---:|---:|---:|---|\n")
	for _, row := range r.Procs {
		newRes := "ok"
		if row.NewErr != "" {
			newRes = row.NewErr
		}
		p("| %s | %d | %d | %.0f | %s | %s | %s | %s |\n", row.Label, row.Workers, row.Samples, row.NsPerSample, f2(row.MCV), f2(row.Cond), f2(row.Shannon), newRes)
	}

	p("\n## Latency\n\n")
	p("| Operation | µs | Notes |\n|---|---:|---|\n")
	for _, row := range r.Latency {
		if row.Err != "" {
			p("| %s | error | %s |\n", row.Name, row.Err)
			continue
		}
		p("| %s | %.3f | %s |\n", row.Name, row.Micros, row.Note)
	}

	if r.GoBench != "" {
		p("\n## go test -bench\n\n```\n%s```\n", r.GoBench)
	}

	p("\n## Method\n\n")
	p("- Throughput reads through `io.ReadFull` into a fixed buffer for at least the window, in batches of at least 4 KiB between clock reads (one read for larger buffers).\n")
	p("- `Uint64` cost is a tight loop over a duration; the racerand rows include the mutex.\n")
	p("- Quality statistics come from `stattest.Analyze`; the NIST tests are the O(n) subset implemented in `stattest.NIST`, with bounded series and continued-fraction calculations for the incomplete gamma function. This is not the official NIST suite.\n")
	p("- Sweeps sample the raw source directly with `Harvester.Sample`, discarding up to 4096 samples as warm-up. Min-entropy figures are estimates, not proofs; the conditional estimate needs many more samples than distinct values and is pessimistic on the full 64-bit samples.\n")
	p("- The duration harness uses one run per point. The embedded Go benchmarks repeat three times by default. Background host activity was not controlled. Race-based entropy depends on the machine, the operating system and what else is running; rerun `make bench` on your own hardware before trusting any of it.\n")
	return b.String()
}
